### ISSUE TITLE
make excludelist error

### ISSUE THREAD

**Issue by gergocs** [Samsung/escargot#1040]
- OS: ArcoLinux
- Revision [f6eeb2c](https://github.com/Samsung/escargot/commit/f6eeb2c1fc6228149233a58908854ab07d19f73c)

**Describe the bug**
Trying to update the exclude list with `make_excludelist.py` but it does not work with python2 nor python3.

With python2 the backtrace:
```
Traceback (most recent call last):
  File "tools/test/test262/make_excludelist.py", line 134, in <module>
    main()
  File "tools/test/test262/make_excludelist.py", line 96, in main
    summary = full.split('=== Test262 Summary ===')[1]
IndexError: list index out of range
```
And the excludelist.orig.xml is empty

With python3 the backtrace:
```
Traceback (most recent call last):
  File "/mnt/D/Munka/escargot/tools/test/test262/make_excludelist.py", line 134, in <module>
    main()
  File "/mnt/D/Munka/escargot/tools/test/test262/make_excludelist.py", line 92, in main
    if full.find('- All tests succeeded') >= 0:
TypeError: argument should be integer or bytes-like object, not 'str'
```

And the end of excludelist.orig.xml is empty(the first 32 lines are good)

**Expected behavior**
Update the excludelist.

**Comment by gergocs** [comment]
Should I update the script to python3 and make it work?

**Comment by clover2123** [comment]
We run `make_excludelist.py` with python2 in Ubuntu environment.
I also run it now and there is no error.
Have you downloaded submodules of escargot?
`test262` (test/test262) submodule should be synced before running the test262

**Comment by clover2123** [comment]
One more thing, have you installed `pypy` on your environment? `make_excludelist.py` internally requires `pypy` for running test262.

**Comment by gergocs** [comment]
I start debugging the code and see what it does and it turns out i gave wrong path for the engine and it didn't give me any error about it. So everything is working now. Thank you.
