### ISSUE TITLE
Temporal with BigInt or With Integer

### ISSUE THREAD

**Issue by gergocs** [Samsung/escargot#1076]
Should i implement [this](https://tc39.es/proposal-temporal/#sec-temporal-createtemporalinstant) function and other functions which are using bigint with bigint or should i use 2 integer?

The standard say it's needed to be BigInt, but BigInt is slow so I thought two integers might be faster.

**Comment by clover2123** [comment]
>8.5.2 CreateTemporalInstant ( epochNanoseconds [ , newTarget ] )
    1. [Assert](https://tc39.es/ecma262/#assert): [Type](https://tc39.es/ecma262/#sec-ecmascript-data-types-and-values)(epochNanoseconds) is BigInt.
    2. [Assert](https://tc39.es/ecma262/#assert): ! [IsValidEpochNanoseconds](https://tc39.es/proposal-temporal/#sec-temporal-isvalidepochnanoseconds)(epochNanoseconds) is true.
    3. If newTarget is not present, set newTarget to %Temporal.Instant%.
    4. Let object be ? [OrdinaryCreateFromConstructor](https://tc39.es/ecma262/#sec-ordinarycreatefromconstructor)(newTarget, "%Temporal.Instant.prototype%", « [[InitializedTemporalInstant]], [[Nanoseconds]] »).
    5. Set object.[[Nanoseconds]] to epochNanoseconds.
    6. Return object.

Above `CreateTemporalInstant` function seems not using any bigint value.
I cannot fully understand the point.
Would you elaborate this issue a bit more?
What is `BigInt`? A type of JavaScript that represents huge numbers or just huge number that can be represented by merging 2 integer values?

**Comment by ksh8281** [comment]
IMO you should use BigInt for implement.
If you want to optimize, you can use int64_t if input number is small

**Comment by gergocs** [comment]
> Would you elaborate this issue a bit more?

For example [here](https://tc39.es/proposal-temporal/#sec-temporal-isvalidepochnanoseconds). 86400 * 10^17 can't be stored in an uint64_t. 

> What is BigInt? A type of JavaScript that represents huge numbers or just huge number that can be represented by merging 2 integer values?

I meant using BigInt from Escargot(src/runtime/BigInt)

**Comment by zherczeg** [comment]
Bascially the question is shall we use an existing BigInt related code (simpler), or use own code (somewhat faster). Most operations are addition / subtraction, and multiply divmod with small numbers (called single digit operations). It is probably not worth to change the code later, so it is better to decide this early.

**Comment by clover2123** [comment]
To sum up, you mean that for relatively small numbers, handle it with simple integer values and for other cases, handle it with BigInt following the standard, right?
This approach seems good for me, but it might be too complicated.
BTW, (I'm not sure) performance of `Temporal` feature does really matter?
If not, I think that simple implementation just with `BigInt` would be enough.
