### ISSUE TITLE
Where is escargot used?

### ISSUE THREAD

**Issue by pedrib** [Samsung/escargot#1140]
Just a question, out of curiosity, where is escargot used? Is it used in any real products, by Samsung or by any other party? It seems to be actively maintained, so I assume it is being used somewhere?

I like to use it for my embedded device builds and experiments.

**Comment by ksh8281** [comment]
Recent Samsung smart tv uses this project. :)

**Comment by pedrib** [comment]
@ksh8281 thank you for your answer. I thought the Samsung Smart TVs (I have two actually!) use a Chromium based browser? At least with a test with one of mine, I got a `AppleWebKit` user-agent string.

**Comment by ksh8281** [comment]
@pedrib It is not made for stock web browser.
This project is used by some applications

**Comment by pedrib** [comment]
Thanks again for letting me know. If you know more use cases, I'd be very curious to know more.
