### ISSUE TITLE
Missed short-circuiting 

### ISSUE THREAD

**Issue by marccarigiet** [Samsung/escargot#1250]
- OS: Ubuntu 20.04  (x86)
 - Revision [[2141345]](https://github.com/Samsung/escargot/commit/2141345fc04ee7c1703c2f4f928f0daa000d97cb)

**describe the Bug**
Expressions of the form: (expression evaluating to false ) && exp1 | exp2,  don't short circuit,

**Test case**

```js
function throwError() {
    throw new Error();
}
false && true | throwError()
```
Or in a smaller case:
```js
false && true | var1 
```
**backtrace**
Uncaught Error:
biggercase.js (3:11)
biggercase.js (5:17)

and respectively

Uncaught ReferenceError: var1 is not defined:
trigger.js (1:17)

**Expected behavior**No error should be thrown, as the && operator should short-circuit and the parts of the expression throwing an error should not be evaluated.

**Comment by ksh8281** [comment]
Thank you for your bug report

**Comment by ksh8281** [comment]
#1251
