### ISSUE TITLE
An issue with await and the detection of Errors

### ISSUE THREAD

**Issue by marccarigiet** [Samsung/escargot#1276]
**Escargot**
 - OS: [Ubuntu 20.04]
 - Revision [4f8582e]

**Describe the bug**
In some cases Errors are not detected after the await keyword.

**Test case**
Some testcases:
```js
await var1;
await of;
await from < from;
await of ^= async ;
```

**Expected behavior**
I'd expect these to throw Errors, mostly Reference Errors.

**Additional context**
First, sorry for the title changes, I prematurely published the issue.
These cases were found using comparative testing with other JavaScript Engines including V8, Spidermonkey and JavaScriptCore. To all my knowledge, this could be intended behavior on your side, but I thought I'd let you know in case it isn't.

**Comment by ksh8281** [comment]
Thanks for reporting issue!
I will resolve this issue!
