### ISSUE TITLE
Inquiry about Security Policy and CVE Management

### ISSUE THREAD

**Issue by rycbar77** [Samsung/escargot#1344]
I have noticed that there are a few CVEs associated with this project assigned by `Samsung TV & Appliance`. However, I was unable to find any documentation or information regarding the project's security policy, such as how to submit security reports and how CVEs are assigned and managed.

Could you please provide some details or point me to the relevant documentation regarding:

- The process for submitting security vulnerabilities.
- The policy or guidelines for handling and disclosing security issues.
- How CVEs are assigned and managed within this project.

**Comment by clover2123** [comment]
Hi! 
For CVE report, please check out the followings:
https://www.cve.org/ReportRequest/ReportRequestForNonCNAs
https://www.cve.org/PartnerInformation/ListofPartners/partner/samsung.tv_appliance
