### ISSUE TITLE
ECMAScript 2016 Internationalization API Specification (ECMA-402)

### ISSUE THREAD

**Issue by clover2123** [Samsung/escargot#251]
## ECMAScript® 2016 Internationalization API Specification 
**ECMA-402 3rd Edition / June 2016**

ECMA-402 Spec : [ecma-402/3rd](https://www.ecma-international.org/ecma-402/3.0/index.html)

Based on the upper spec, we are going to update/implement ECMA-402 Intl features one by one. 

- [x] Collation
- [x] Number Formatting
- [x] Currency Formatting
- [x] Date/Time Formatting

**Comment by clover2123** [comment]
Current `Intl` in Escargot is not fully supported.  So, we are going to update/implement Intl features together with ES6. If anyone is interested in this issue, please join it and update together. 

To avoid any conflict, please announce your work/plan at here before updating each feature. Thanks:)

**Comment by pmarkee** [comment]
Question: are these features currently tested? Where should we add internal TCs? In `test/es2015` directory, or should we create a separate test directory ( for example `test/intl` )?

**Comment by clover2123** [comment]
@pmarkee There are no TCs for Intl now. #260 looks nice :)
