### ISSUE TITLE
Uint8ClampedArray values are not clamped correctly

### ISSUE THREAD

**Issue by Achie72** [Samsung/escargot#273]
**OS:** Ubuntu 16.04 LTS
**Escargot version:** 54f7a35
**cmake version:** 3.5.1

**Build commad:**
`cmake -DESCARGOT_HOST=linux -DESCARGOT_ARCH=x64 -DESCARGOT_MODE=debug -DESCARGOT_OUTPUT=bin -GNinja && ninja`

---

**Example:**
```js
var a = new Uint8ClampedArray([-12,344,1.5,1.4])
print(a)
```
**Expected result:**
`0, 255, 2, 1`
[(ECMA 2015)](https://www.ecma-international.org/ecma-262/6.0/#sec-touint8clamp)

**Given result:**
`244,88,1,1`

---

It is possible, that the project does not have it implemented yet, and it falls back to basic `uint_8` (which gives the same results), but in the codebase, there are functions and adaptors, that are indicating that we have a ClampedArray type. (such as can be seen in TypedArrayObject.h, [here](https://github.com/pando-project/escargot/blob/master/src/runtime/TypedArrayObject.h#L33) and [here](https://github.com/pando-project/escargot/blob/master/src/runtime/TypedArrayObject.h#L430))

**Comment by clover2123** [comment]
Thanks for the report. If you are not working on it, I'll take a look at this issue.

**Comment by Achie72** [comment]
I'm not working on it at the moment, i discovered this, while working on #274, but as it seems different from it, so i did not want to solve it in that PR. Feel free to pick it up.
