### ISSUE TITLE
Infinite loop: `a: { continue a }` 

### ISSUE THREAD

**Issue by zherczeg** [Samsung/escargot#330]
Normally continue with label should only work with iterable statements, but in Escargot any statement can be "restarted". I think we should fix this.

However there is some exception which can be thrown during the code generation, and that triggers some issue with `switch` statements. What is the purpose of that? Shall we fix this during code generation (late) or at parsing time (early)?

**Comment by ksh8281** [comment]
Good catch....
I think this is one of esprima's bug
I tested `a: { continue a }` on esprima.org, but it didn't throw any error.
We should fix this in parsing time(early) I think.
