### ISSUE TITLE
Updated readme.md

### ISSUE THREAD

**Issue by Seo-Young** [Samsung/escargot#335]
Hi this is Isabelle on behalf of Samsung Inner Source Program.
According to the Inner Source Program Governance. I would like to make PR for readme. 
But it just committed. 
Please check your project members has no issue with the changes. And please add copyright file of this project on the master node with the direction in this page : http://mosaic.sec.samsung.net/kms/comty.do?comtyId=279217135&menuId=324418265&postId=357870588&page=view&type=LIST&access=ADDRESS
Once above written things done, your submission will be finalized.

**Comment by haesik** [comment]
We have decided not to participate in the inner source program of samsung because escargot is open source project.
