### ISSUE TITLE
Update ECMAScript 6 Features

### ISSUE THREAD

**Issue by clover2123** [Samsung/escargot#51]
## ES6 Features on Escargot

ES6 Spec : [ecma-262/6.0](https://www.ecma-international.org/ecma-262/6.0/)
ES6 New Features : [New Features Overview & Comparison](http://es6-features.org)

Based on the upper spec, we are going to update ES6 features one by one. 
Current status of implemented/unimplemented ES6 features are as follows.

### Implementation Priority

1. **`const` / `let` variables** (widely used, but also most difficult)
2. Classes
3. Generators
4. Modules

### Current Status of ES6 Features
ES6 Feature List based on [New Features Overview & Comparison](http://es6-features.org)

**Constants**
- [x] `const` Variables

**Scoping**
- [x] `let` Variables
- [x] Block scoped function definitions

**Arrow Function**
- [x] Arrow function

**Extended Parameter Handling**
- [x] Default parameter
- [x] Rest parameter
- [x] Spread operator

**Template Literals**
- [x] String interpolation
- [x] Custom interpolation
- [x] Raw string access

**Extended Literals**
- [x] Binary & Octal Literal
- [x] Unicode String & RegExp Literal

**Enhanced Regular Expression**
- [x] Regular Expression Sticky Matching

**Enhanced Object Properties**
- [x] Property Shorthand
- [x] Computed Property Names
- [x] Method Properties

**Destructuring Assignment**
- [x] Array Matching
- [x] Object Matching
- [x] Parameter Context Matching
- [x] Fail-Soft Destructuring

**Modules**
- [x] Value Export/Import
- [x] Default & Wildcard

**Classes**
- [x] Class Definition
- [x] Class Inheritance
- [x] Base Class Access
- [x] Static Members
- [x] Getter/Setter

**Symbol Type**
- [x] Symbol Type (**partially implemented**)
- [x] Global Symbols (**partially implemented**)

**Iterators**
- [x] Iterator & For-Of Operator

**Generators**
- [x] Generator Function, Iterator Protocol
- [x] Generator Function, Direct Use
- [x] Generator Matching
- [x] Generator Control-Flow
- [x] Generator Methods

**Map/Set & WeakMap/WeakSet**
- [x] Set Data-Structure 
- [x] Map Data-Structure
- [x] Weak-Link Data-Structures

**Typed Arrays**
- [x] Typed Arrays

**New Builtin Methods**
- [x] Object Property Assignment
- [x] Array Element Finding
- [x] String Repeating
- [x] String Searching
- [x] String Normalization
- [x] Number Type Checking
- [x] Number Safety Checking
- [x] Number Comparison
- [x] Number Truncation
- [x] Number Sign Determination

**Promises**
- [x] Promise Usage (**partially implemented**)
- [x] Promise Combination (**partially implemented**)

**Meta-Programming**
- [x] Proxy
- [x] Reflect

**Internationalization & Localization**
- [x] Collation
- [x] Number Formatting
- [x] Currency Formatting
- [x] Date/Time Formatting

**NOTE**
- The above list may miss some ES6 features or mark already implemented features as unimplemented. 
- Please mark an check-box after completely update each feature.
- Add related TC when each feature is updated

**Comment by rerobika** [comment]
@clover2123 Could you please update this TODO list with these features?

- Binary & Octal Literal
- Regular Expression Sticky Matching
- Property Shorthand
- Array Matching
- Object Matching
- Parameter Context Matching
- Fail-Soft Destructuring
- Class Definition
- Class Inheritance
- Base Class Access
- Static Members
- Getter/Setter

**Comment by clover2123** [comment]
@rerobika I've updated the list. Thanks:)

**Comment by clover2123** [comment]
`Implementation Priority` list is newly added. ES6 features in the list are commonly used, so it would be better to update the list in high priority first if possible.

**Comment by rerobika** [comment]
@clover2123 To avoid conflicts I've started to work on the let/const.

**Comment by rerobika** [comment]
@clover2123 Could you please update this TODO list with these features?

- Unicode String & RegExp Literal
- Regular Expression Sticky Matching
- Generator Function, Iterator Protocol
- Generator Function, Direct Use
- Generator Matching
- Generator Control-Flow
- Generator Methods

**Comment by clover2123** [comment]
@rerobika List updated. Thanks:)

**Comment by rerobika** [comment]
@clover2123 @ksh8281  @bbrto21 Are you started/planning to work on the ES6 module system? If not and you do not mind, I'll start working on it.

**Comment by ksh8281** [comment]
@rerobika no.. you won't
we don't want to add new feature right now.
we want to pass every test262(only implemented features)
and we want to run very huge program (like big websites. youtube..google...)
so we need to run every program on fast mode(indexed mode)

you can choose finding bug on already implemented features(class, rest, arrow..)
or turn on fast mode es6 features.

If we cannot on fast mode, we cannot use this project(es6 features) for real product...(because too slow to use..)

**Comment by zherczeg** [comment]
Hi @ksh8281, do you have any benchmarks where we should measure the improvement?

**Comment by ksh8281** [comment]
@zherczeg we don't have es6 bench marks yet. do you have any idea? 
but we can observe we give up fast(indexed) mode when many es6 features(pattern, rest, arrow super...) comes up with source

**Comment by clover2123** [comment]
Escargot now supports ESMAScript 2015 completely from the [release 1.6.0](https://github.com/Samsung/escargot/releases/tag/v1.6.0). Close this issue.
