### ISSUE TITLE
Function release

### ISSUE THREAD

**Issue by zherczeg** [Samsung/escargot#613]
If I run the following code:
```
function f() {
}
f();
```

The finalizer runs for the program, but not for `f`:
https://github.com/Samsung/escargot/blob/master/src/interpreter/ByteCode.cpp#L93

If I throw an exception in `f`, the finalizer also runs for the byte code created temporarily, but still no release for `f`. Do you have idea what is happening here?

**Comment by ksh8281** [comment]
The finalizer runs for the program, but not for f
->
The compiled program bytecode can not be used after execution.
so we give up program bytecode at Script.cpp(Script::execute)
```
    // we give up program bytecodeblock after first excution for reducing memory usage
    m_topCodeBlock->m_byteCodeBlock = nullptr;
```

but compiled function bytecode is differ
many functions are re-executed so we don't give up even it was executed.
but we sometimes give up compiled function bytecodes at VMInstance::gcEventCallback
this is why function bytecode finalizer is not called by gc

If I throw an exception in f, the finalizer also runs for the byte code created temporarily, but still no release for f. Do you have idea what is happening here?
->
We should not save `indexes of ByteCode to source code` for reducing ByteCodeBlock
thus we should gather source positions when we want to know source positions
we can gather `indexes of ByteCode to source code` when ByteCode are generated
when gather `indexes of ByteCode to source code`, we should not replace ByteCodeBlock but we replace content of the ByteCodeBlock. 
thats why finalizer is not called by gc

**Comment by zherczeg** [comment]
Thank you. So it is not possible to tell that those functions are not used anymore.
