### ISSUE TITLE
Incorrect backtrace line-columns info

### ISSUE THREAD

**Issue by rerobika** [Samsung/escargot#649]
- OS: Ubuntu 18.04
 - Revision 66d95455d7e5457e9c31b1214dec457e4f73c08c

**Describe the bug**

**Test case**
Test code to reproduce the behavior:
```js
/*1*/function f() {
/*2*/  print ("f");
/*3*/}
/*4*/function g() {
/*5*/  throw 4;
/*6*/}
/*7*/g();
```

**Backtrace**
```
Uncaught 4:
issue.js (6:7)
issue.js (7:6)
```

**Expected behavior**
```
Uncaught 4:
issue.js (5:8)
issue.js (7:6)
```

However, that line misalignment wouldn't be a huge problem in the CLI version of the engine, but currently it's a major problem in the VSCode debugger adapter. In the VSCode adapter the active line selection - where the execution currently has been paused, marked with green/yellowish background-, is calculated by the backrace-info first frame.

![image](https://user-images.githubusercontent.com/22135179/81153027-cd3bf300-8f82-11ea-8966-d57d19352ba5.png)

However, when stepping into to `g()` the incorrect backtraceinfo leads to this behaviour:

![image](https://user-images.githubusercontent.com/22135179/81153370-2572f500-8f83-11ea-8a73-efcab968be04.png)

So my question is is there any way to improve the backtrace info to give precise at least line info? That's currenly only a pending question, the related work on this task highly depends on the answer, and the assumed amount of time to fix this problem.

**Comment by clover2123** [comment]
Hello!
When I test your sample code by escargot (revision 66d9545), it shows the backtrace info correctly as follows.
```
Uncaught 4:
test.js (5:8)
test.js (7:6)
```
Is this problem occurred only for debugger?
Would you please explain the case more specifically when it is occurred?

**Comment by zherczeg** [comment]
I also tried this test, and get the former output (with `issue.js (6:7)`). This is my cmake command:

`cmake -DCMAKE_C_COMPILER=gcc-9 -DCMAKE_CXX_COMPILER=g++-9 -DESCARGOT_HOST=linux -DESCARGOT_MODE=release -DESCARGOT_ARCH=x86 -DESCARGOT_OUTPUT=shell -GNinja``

Debugger is not enabled. I tried both `debug` and `release` modes and both `x86` and `x64` but I still get the same output. How do you compile Escargot?

**Comment by clover2123** [comment]
I tried `debug` and `release` mode too.
I run the sample file(`issue.js`) with standalone escargot.

My compile command :
"cmake -DESCARGOT_HOST=linux -DESCARGOT_ARCH=x64 -DESCARGOT_MODE=debug -DESCARGOT_OUTPUT=shell_test -GNinja"

**Comment by zherczeg** [comment]
We finally able to track it down. It turned out even if we don't specify `-DESCARGOT_DEBUGGER=1`, it is somewhere in the cmake cache, and somehow emitting disabled breakpoints cause the line info issues.
