### ISSUE TITLE
Updating Unicode Identifier Ranges

### ISSUE THREAD

**Issue by Achie72** [Samsung/escargot#656]
There is a little kangax example, that i'm working on:
```js
var 𐋀;
```
which tests if we can allow this 32 unicode as an identifier:
[https://www.fileformat.info/info/unicode/char/102c0/index.htm](https://www.fileformat.info/info/unicode/char/102c0/index.htm)

I started a pull request, but got stuck a bit, as seeing this is not registered as an identifier starter i tried to use something along the line of [getComplexIdentifier](https://github.com/Samsung/escargot/blob/master/src/parser/Lexer.cpp#L789) from Lexer, but that messes up escargot quite  a bit.

So i was wondering if we have tools to just simply update our tables about unicode characters. As escargot is a bit more robust, i think it can handle a bit bigger tables, so these kind of characters can be used as well. I was looking for some script, with which i can update the tables in Lexer.cpp, but could not find any, so i just wanted to ask if you have an internal script for generating those, as updating them by hand is much more tedious and not really a long term option, as these update quite often.

**Comment by clover2123** [comment]
Unfortunately, there is no script which automatically updates the unicode table ([g_asciiRangeCharMap](https://github.com/Samsung/escargot/blob/bfcc61254d251c536a1c8de369b6a09bf6228026/src/parser/Lexer.cpp#L42)).

To give a small tip, Escargot scanner reflects that of esprima too.
We use the `g_asciiRangeCharMap` table only for scanning performance but esprima does not.
You may update the table more easily with reference to the esprima scanner as follows.
https://github.com/jquery/esprima/blob/45c9ab14d96f7f7fa88333fdd897487a8c20082f/src/character.ts#L34-L49
