### ISSUE TITLE
[Debugger] ESCARGOT_MESSAGE_RELEASE_FUNCTION triggered while receiving the source code

### ISSUE THREAD

**Issue by clover2123** [Samsung/escargot#702]
**Escargot (please complete the following information):**
 - OS: Ubuntu 16.04
 - Related PR : #701 

**Describe the bug**
#701 initially failed only for the debugger's `client_source_multiple` test case as follow.
![image](https://user-images.githubusercontent.com/29055659/86985958-6b3f7a00-c1cd-11ea-9486-215186324bc4.png)

**Test case**
Test code to reproduce the behavior:
```sh
build/debugger_out_linux64/escargot --start-debug-server --debugger-wait-source
tools/debugger/debugger.py --verbose --client-source tools/debugger/tests/client_source_multiple_2.js tools/debugger/tests/client_source_multiple_1.js
```
I reproduced the error case by running the above commands (with verbose option).
The below is the result log messages.
![image](https://user-images.githubusercontent.com/29055659/86986329-60d1b000-c1ce-11ea-870d-bc4e101a8093.png)

I found that the first js file (client_source_multiple_2.js) was loaded and executed well
but right after entering `n` (next) command, the error ocurred.
While loading the second js file (client_source_multiple_1.js) unexpected `ESCARGOT_MESSAGE_RELEASE_FUNCTION` is received and debugger throws an error since `_parse_source` module of debugger does not have a routine for this message.

`ESCARGOT_MESSAGE_RELEASE_FUNCTION` is triggered when each `ByteCodeBlock` is freed.
And Escargot currently sets the ByteCodeBlock of global code as nullptr right after running it.
https://github.com/Samsung/escargot/blob/747803bf81492f0c4735d0e15586ccf80664b3b8/src/parser/Script.cpp#L406-L407

When about to execute the second js file (client_source_multiple_1.js) after `n` command entered,
Escargot starts to send the source code to the debugger.
During this task, the source code and file name are delivered by allocating each `StringView` object.
Since `StringView` is GC object, it may trigger GC and GC sequantially reclaims the global ByteCodeBlock of the first js file.
So, `ESCARGOT_MESSAGE_RELEASE_FUNCTION` is triggered in the middle of sending the source code and this is the main culprit.

PR #701 modified some GC objects and it could affect the timing of GC events.
When I fix the ByteCodeBlock of global code not to be set as nullptr, the error is not occurred again.
I think that this error is coincidence (rare case) but needs to be fixed.
But I'm not sure what the best solution is.
All ideas are welcome :)

**Comment by clover2123** [comment]
@zherczeg @kisbg  @rerobika 
Would you please check this issue?

**Comment by zherczeg** [comment]
You analysis is correct handling ESCARGOT_MESSAGE_RELEASE_FUNCTION is missing from the parser. But it is a possible command there.
